### PR TITLE
Update platformio.ini for nodo board

### PR DESCRIPTION
**Pull request by tjfsteele**
Add an env: for the board sold by nodo-shop.nl

### CODE REVIEW

**Comment by danielkucera** [comment]
This one? https://www.nodo-shop.nl/en/our-products/260-lorawan-gateway.html

Nice! Is that your shop? :)

**Comment by tjfsteele** [comment]
Not my shop, but I design PCBs for them

**Comment by tjfsteele** [comment]
Full kit: https://www.nodo-shop.nl/en/our-products/259-lorawan-gateway.html

**Comment by dennis4lora** [comment]
Thanks! And nice to know the kit, simple yet very grace design.  👍

**Comment by dennis4lora** [comment]
Thanks! And nice to know the kit, simple yet very grace design.  👍

**Pull request merged**
