### PR TITLE
Add support for ESP32C3

### PR DESCRIPTION
**Pull request by danielkucera**

### CODE REVIEW

**Comment by dennis4lora** [comment]
@danielkucera Thanks for your great work.  :+1: 

I see no problem to the changes to most files except file **sdkconfig** feels like been replaced by mistake. Can you help to check? Thanks.

**Comment by danielkucera** [comment]
I wanted it to only contain non-default values, the rest are defaults.
At least that is how it works with platformio.

**Comment by dennis4lora** [comment]
OK, that way should be all right.

However, I don't know why but my esp32 keeps reboot with this modification as well as #7 (no problem for #6). I need to double check it tomorrow...

**Comment by dennis4lora** [comment]
The reason of my device rebooting is because malloc() failed for conf_array. Let's back to #7 to discuss it.
This PR has no problem, so let me merge it. Thanks. :smile:

**Pull request merged**
