### PR TITLE
memory optimizations

### PR DESCRIPTION
**Pull request by danielkucera**
Moves all binary blobs from RAM to flash and removes some static allocation.

Before:
RAM:   [=====     ]  47.9% (used 156904 bytes from 327680 bytes)
Flash: [========= ]  89.5% (used 938153 bytes from 1048576 bytes)

After:
RAM:   [===       ]  27.6% (used 90520 bytes from 327680 bytes)
Flash: [========= ]  89.5% (used 938277 bytes from 1048576 bytes)

### CODE REVIEW

**Comment by danielkucera** [comment]
@dennis4lora ,
I was also thinking about changing the storage of all those binary/huge assets.

I would start by adding a spiff storage containing a default json config which could be directly edited (using html text box) and removing the separate config options for frequency, server, port etc.

What do you think about that?

**Comment by dennis4lora** [comment]
Thanks. I think this change is truly a very big improvement for the memory usage!

> I would start by adding a spiff storage containing a default json config which could be directly edited (using html text box) and removing the separate config options for frequency, server, port etc.

> What do you think about that?

I agree that for the json config files, there are many places to improve the current design, and that the current way has some should-not-exist restrictions. I just haven't think it enough since I want to finish the update to v2.1 first. :-)

My original idea is put simplicity ahead of flexibility, and those options can kind of preventing users to input wrong values or be confused if providing a whole json file to them. But to support full customization (as well as for supporting other regions), I once thought that maybe I can provides an "export(download) - edit - import (upload)" way for that purpose.

Your idea is obviously a solution, and I think it's doable. But I guess we need to firstly make sure that **if the user makes a mistake (such as makes the config doesn't follow the correct json format any more), we can detect it and refuse to accept it**. 

As long as users can't crash it easily, we should provide as much flexibility as possible. :smile:

**Comment by danielkucera** [comment]
This PR is ready.

Regarding the config, I think we could concentrate all the config (maybe except the wifi?) into single json and build a robust validation (it wouldn't save when validation fails) and customization (specific parameters, as those currently in the web interface, saved into that json) around that with a fallback to defaults. But this is for another PR.

Besides this, I have a port to different MCUs in the pipeline. Currently I have a working branch with ESP32C3.

**Comment by dennis4lora** [comment]
@danielkucera 
On my side, the `malloc()` for **conf_array** returns NULL. I need to check the reason (heap too small?).

Also, that `malloc()` maybe is unnecessary since none of the original 3 const static arrays needs to be changed, so we can refer to the right one directly, right?
 
I think the only time we need to change such array is when assembling the web page content before returning to the browser. We can use malloc() there to save some space (replace **resp_buf[10240]** in `main/http_server.c`), but that's another optimization.

**Comment by danielkucera** [comment]
Actually, it is being edited, for example here:
https://github.com/lora-gateway/esxp1302/blob/main/main/main.c#L1478
That's why I was suggesting to use the config from spiffs so we can do memory intensive edits/replacements only during config save or on the client side.

**Comment by dennis4lora** [comment]
@danielkucera 
You are right that it's being edited; I have forgotten how I designed it long time ago and didn't checked it carefully...
I also found the reason why **conf_array** is `NULL` on my side and fixed it.

The spiffs way feels no a bad idea and should be able to make the whole process a little more "natural". :-)

**Comment by danielkucera** [comment]
> I also found the reason why **conf_array** is `NULL` on my side and fixed it.

Oh, I see in the master, I think I know how this slipped my attention... Sorry for that.

I'll try to prepare something with the spiff so we can discuss.

**Pull request merged**
